server:
  port: 8083

spring:
  application:
    name: libraryManagement

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 12345
    locations: classpath:db/migration





