create table books(
    id int generated by default as identity primary key,
    title varchar(255) not null,
    author varchar(64) not null,
    year integer not null,
    isbn varchar(20) not null
);